#numpy-->numerical python
erişim içimn [tıklayınız](https://numpy.org/learn/)

Numpy, Python'da bilimsel hesaplama için kullanılan bir kütüphanedir ve çok boyutlu diziler (arrays) ile çalışmayı sağlar.



In [ ]:
#pip install numpy# kütüphane yükleme

import numpy as np # kütüphane yükleme anlık nesne türetme
#import tensorflow
#import keras

In [ ]:
class Insan:
  #ad,soyad,tc--field, özellik, propoert

  #def--> fonksiyon,yapıcı

1. **Numpy Dizisi (Array) Oluşturma**
Bir listeyi numpy dizisine dönüştürmek:



In [ ]:
my_list = [1, 2, 3, 4, 5] #sayı lste--->1 satır, 5 sütunluk vector/dizi #tek boyutlu
np_array = np.array(my_list)
print(np_array)
# Çıktı:


[1 2 3 4 5]


In [ ]:
my_list[0]

1

In [ ]:
my_list2 = [[0,1,2,3,4],
            [1, 2, 3, 4, 5]] #sayı 2 boyutlu 2,5 #çok boyutlu
np_array2 = np.array(my_list2)
print(np_array2)

0'larla dolu bir dizi oluşturmak:


In [ ]:
zeros = np.zeros()
print(zeros)

[0. 0. 0. 0. 0.]


1'lerle dolu bir dizi oluşturmak:


In [ ]:
ones = np.ones(5)
print(ones)

[1. 1. 1. 1. 1.]


**Belirli bir aralıkta değerler içeren bir dizi oluşturmak:**


In [ ]:
arange_array = np.arange(0, 10, 2)
print(arange_array)

[0 2 4 6 8]


0 ile 1 arasında eşit aralıklarla 5 sayı oluşturmak:



In [ ]:
linspace_array = np.linspace(0, 10, 5)
print(linspace_array)

[ 0.   2.5  5.   7.5 10. ]


3. **Numpy Dizilerinde Matematiksel İşlemler**


In [ ]:
arr = np.array([1, 2, 3, 4])# 1,4 matris #  tek boyutlu
print(arr + 2)
# Çıktı:

print(arr - 1)
# Çıktı:  0 1 2 3

print(arr * 3)
# Çıktı:

print(arr / 2)
# Çıktı:


4. Numpy Dizilerinin Özellikleri


In [ ]:
#Dizinin şekli (shape):

arr = np.array([[1, 2, 3], [4, 5, 6]])  # çok boyutlu matris
print(arr.shape)
# Çıktı: (2, 3)  # 2 satır, 3 sütun

#Eleman sayısı (size):

print(arr.size)
# Çıktı: 6

#Eleman tipi (dtype):

print(arr.dtype)
# Çıktı: int64 (elemanların türü)


5. Numpy ile Rastgele Sayılar


In [ ]:
random_numbers = np.random.rand(5) #0 ile 1 arasında rastgele sayılar:
print(random_numbers)


[0.67861665 0.16498079 0.29137682 0.46271281 0.80467653]


In [ ]:
random_integers = np.random.randint(1, 10, 5) #belirli aralıkta rastgele sayı
print(random_integers)
# Çıktı: Örneğin [3 7 1 5 9]


6. Numpy Matris İşlemleri


In [ ]:
A = np.array([[1, 2], [3, 4]])#2,2
B = np.array([[5, 6], [7, 8]])

C = np.dot(A, B)      #matris çarpımı
print(C)

[[19 22]
 [43 50]]


In [ ]:
C.T

array([[19, 43],
       [22, 50]])

In [ ]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
print(A.T)#transpoze


[[1 3]
 [2 4]]


7. Numpy Dizilerinde İndeksleme ve Dilimleme


In [ ]:
arr = np.array([10, 20, 30, 40, 50])  # tek bboyutlu dizi--vektör
print(arr[1])
print(arr[1:4])

20
[20 30 40]


In [ ]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # çok bboyutlu dizi--matris 3*3-->3 matris
print(arr2[0, 1])
print(arr2[:2, 1:])


2
[[2 3]
 [5 6]]


8. Numpy'da Fonksiyonlar


In [ ]:
print(np.max(arr)) # max
print(np.min(arr)) #min
print(np.mean(arr))  # Ortalama
print(np.sum(arr))   # Toplam
print(np.std(arr))   # Standart sapma

50
10
30.0
150
14.142135623730951


#pandas


Pandas, veri analizi ve veri işleme için kullanılan popüler bir Python kütüphanesidir. Veri manipülasyonu ve analizi için DataFrame ve Series yapıları sağlar

kendi dökümanınına ulaşmak için
[tıklayınız](https://pandas.pydata.org/docs/)

In [ ]:
#pip install pandas
import pandas as pd

1. Pandas Series ve DataFrame


In [ ]:
import pandas as pd

# Liste ile Series oluşturma
my_series = pd.Series([10, 20, 30, 40])
print(my_series)


0    10
1    20
2    30
3    40
dtype: int64


DataFrame: İki boyutlu veri yapısıdır (tablolar gibi). Satır ve sütunlardan oluşur.



In [ ]:
# Sözlük ile DataFrame oluşturma # dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age':  [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}

df = pd.DataFrame(data)
print(df)


      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago


3. CSV Dosyasını Okuma ve Yazma


In [ ]:
import pandas as pd


In [ ]:
df = pd.read_csv('data.csv')
dfe=pd.read_excel('data.xlsx')
#df.to_csv('output.csv', index=False)


4. basit işlemler

In [ ]:
df.head()# df.head(2)  varsayılan olarak 5 adet gelir, İlk birkaç satırı görüntülemek
df.tail()
df.shape
df.columns


In [ ]:
ages = df['Age'] #Belirli bir sütunu seçme
print(ages)


0    25
1    30
2    35
Name: Age, dtype: int64


In [ ]:
selected_columns = df[['Name', 'City']] #Birden fazla sütun seçmek:
print(selected_columns)


      Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago


In [ ]:
#Koşullu seçim yapma
adults = df[df['Age'] >= 30]
print(adults)


      Name  Age         City
1      Bob   30  Los Angeles
2  Charlie   35      Chicago


In [ ]:
#Belirli bir değeri değiştirmek:
df.loc[df['Name'] == 'Alice', 'Age'] = 26


6. DataFrame Üzerinde İstatistiksel İşlemler


In [ ]:
print(df['Age'].mean())  # Yaşların ortalaması
print(df['Age'].sum())   # Yaşların toplamı
print(df['Age'].min())   # En küçük yaş
print(df['Age'].max())   # En büyük yaş


In [ ]:
grouped = df.groupby('City')['Age'].mean() #Gruplama işlemi

print(grouped)


City
Chicago        35.0
Los Angeles    30.0
New York       25.0
Name: Age, dtype: float64


In [ ]:
import matplotlib as mt
import seaborn as sns

7. Eksik Verilerle Çalışmak


In [ ]:
df.isnull().sum() #Eksik değerleri kontrol etmek:

In [ ]:
df['Age'].fillna(df['Age'].mean(), inplace=True) #Eksik değerleri doldurmak:

In [ ]:
df.dropna(inplace=True) #Eksik değerleri içeren satırları silmek:

8. DataFrame’i Sıralamak


In [ ]:
#Belirli bir sütuna göre sıralamak:


df.sort_values('Age', ascending=False, inplace=True)

9. DataFrame Üzerinde Satır ve Sütun Ekleme


In [ ]:
#Yeni sütun eklemek:

df['NewColumn'] = [1, 2, 3]

In [ ]:
#Satır eklemek (append kullanarak):
new_row = {'Name': 'David', 'Age': 40, 'City': 'San Francisco'}
df = df.append(new_row, ignore_index=True)



# en çok kullanılan pandas fonksiyonları

In [ ]:
#Verinin genel bilgilerini almak:


df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 200.0+ bytes


In [ ]:
#Tanımlayıcı istatistikleri almak:


df.describe()


Age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0

# sayısal olmayan değerleri encode
# kategorik değerleri sayısal değerlere dönüştürme
> label encoding

> one hot encoding

bilgi için [tıklayınız](https://serdartafrali.medium.com/veri-biliminde-encoding-i%CC%87%C5%9Flemleri-616e87bf8c74)

**db**

Kaggle kidney db:[tıklayınız](https://www.kaggle.com/datasets/figolm10/kidney-dataset/code)




In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#pip install numpy

In [ ]:
pip install numpy

In [ ]:
import pandas as pd

#df = pd.read_csv('/content/drive/MyDrive/veri bilimine giris/3.Hafta/kidney_disease.csv')
#localde aynı klasörde
df = pd.read_csv('kidney_disease.csv')


In [ ]:
df.head()

id   age    bp     sg   al   su     rbc        pc         pcc          ba  \
0   0  48.0  80.0  1.020  1.0  0.0     NaN    normal  notpresent  notpresent   
1   1   7.0  50.0  1.020  4.0  0.0     NaN    normal  notpresent  notpresent   
2   2  62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent  notpresent   
3   3  48.0  70.0  1.005  4.0  0.0  normal  abnormal     present  notpresent   
4   4  51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent  notpresent   

   ...  pcv    wc   rc  htn   dm  cad appet   pe  ane classification  
0  ...   44  7800  5.2  yes  yes   no  good   no   no            ckd  
1  ...   38  6000  NaN   no   no   no  good   no   no            ckd  
2  ...   31  7500  NaN   no  yes   no  poor   no  yes            ckd  
3  ...   32  6700  3.9  yes   no   no  poor  yes  yes            ckd  
4  ...   35  7300  4.6   no   no   no  good   no   no            ckd  

[5 rows x 26 columns]

In [ ]:
df.head(1)# yapıcı metoda parametre yolluyorum.  #metot overloading

id   age    bp    sg   al   su  rbc      pc         pcc          ba  ...  \
0   0  48.0  80.0  1.02  1.0  0.0  NaN  normal  notpresent  notpresent  ...   

   pcv    wc   rc  htn   dm  cad appet  pe ane classification  
0   44  7800  5.2  yes  yes   no  good  no  no            ckd  

[1 rows x 26 columns]

In [ ]:
df.tail()

id   age    bp     sg   al   su     rbc      pc         pcc          ba  \
395  395  55.0  80.0  1.020  0.0  0.0  normal  normal  notpresent  notpresent   
396  396  42.0  70.0  1.025  0.0  0.0  normal  normal  notpresent  notpresent   
397  397  12.0  80.0  1.020  0.0  0.0  normal  normal  notpresent  notpresent   
398  398  17.0  60.0  1.025  0.0  0.0  normal  normal  notpresent  notpresent   
399  399  58.0  80.0  1.025  0.0  0.0  normal  normal  notpresent  notpresent   

     ...  pcv    wc   rc  htn  dm  cad appet  pe ane classification  
395  ...   47  6700  4.9   no  no   no  good  no  no         notckd  
396  ...   54  7800  6.2   no  no   no  good  no  no         notckd  
397  ...   49  6600  5.4   no  no   no  good  no  no         notckd  
398  ...   51  7200  5.9   no  no   no  good  no  no         notckd  
399  ...   53  6800  6.1   no  no   no  good  no  no         notckd  

[5 rows x 26 columns]

In [ ]:
df.shape

(400, 26)

In [ ]:
df.describe()

id         age          bp          sg          al          su  \
count  400.000000  391.000000  388.000000  353.000000  354.000000  351.000000   
mean   199.500000   51.483376   76.469072    1.017408    1.016949    0.450142   
std    115.614301   17.169714   13.683637    0.005717    1.352679    1.099191   
min      0.000000    2.000000   50.000000    1.005000    0.000000    0.000000   
25%     99.750000   42.000000   70.000000    1.010000    0.000000    0.000000   
50%    199.500000   55.000000   80.000000    1.020000    0.000000    0.000000   
75%    299.250000   64.500000   80.000000    1.020000    2.000000    0.000000   
max    399.000000   90.000000  180.000000    1.025000    5.000000    5.000000   

              bgr          bu          sc         sod         pot        hemo  
count  356.000000  381.000000  383.000000  313.000000  312.000000  348.000000  
mean   148.036517   57.425722    3.072454  137.528754    4.627244   12.526437  
std     79.281714   50.503006    5.741126   10.408752    3.193904    2.912587  
min     22.000000    1.500000    0.400000    4.500000    2.500000    3.100000  
25%     99.000000   27.000000    0.900000  135.000000    3.800000   10.300000  
50%    121.000000   42.000000    1.300000  138.000000    4.400000   12.650000  
75%    163.000000   66.000000    2.800000  142.000000    4.900000   15.000000  
max    490.000000  391.000000   76.000000  163.000000   47.000000   17.800000

In [ ]:
df.describe().T

count        mean         std     min     25%     50%     75%      max
id    400.0  199.500000  115.614301   0.000   99.75  199.50  299.25  399.000
age   391.0   51.483376   17.169714   2.000   42.00   55.00   64.50   90.000
bp    388.0   76.469072   13.683637  50.000   70.00   80.00   80.00  180.000
sg    353.0    1.017408    0.005717   1.005    1.01    1.02    1.02    1.025
al    354.0    1.016949    1.352679   0.000    0.00    0.00    2.00    5.000
su    351.0    0.450142    1.099191   0.000    0.00    0.00    0.00    5.000
bgr   356.0  148.036517   79.281714  22.000   99.00  121.00  163.00  490.000
bu    381.0   57.425722   50.503006   1.500   27.00   42.00   66.00  391.000
sc    383.0    3.072454    5.741126   0.400    0.90    1.30    2.80   76.000
sod   313.0  137.528754   10.408752   4.500  135.00  138.00  142.00  163.000
pot   312.0    4.627244    3.193904   2.500    3.80    4.40    4.90   47.000
hemo  348.0   12.526437    2.912587   3.100   10.30   12.65   15.00   17.800

In [ ]:
df.isnull()

id    age     bp     sg     al     su    rbc     pc    pcc     ba  \
0    False  False  False  False  False  False   True  False  False  False   
1    False  False  False  False  False  False   True  False  False  False   
2    False  False  False  False  False  False  False  False  False  False   
3    False  False  False  False  False  False  False  False  False  False   
4    False  False  False  False  False  False  False  False  False  False   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
395  False  False  False  False  False  False  False  False  False  False   
396  False  False  False  False  False  False  False  False  False  False   
397  False  False  False  False  False  False  False  False  False  False   
398  False  False  False  False  False  False  False  False  False  False   
399  False  False  False  False  False  False  False  False  False  False   

     ...    pcv     wc     rc    htn     dm    cad  appet     pe    ane  \
0    ...  False  False  False  False  False  False  False  False  False   
1    ...  False  False   True  False  False  False  False  False  False   
2    ...  False  False   True  False  False  False  False  False  False   
3    ...  False  False  False  False  False  False  False  False  False   
4    ...  False  False  False  False  False  False  False  False  False   
..   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
395  ...  False  False  False  False  False  False  False  False  False   
396  ...  False  False  False  False  False  False  False  False  False   
397  ...  False  False  False  False  False  False  False  False  False   
398  ...  False  False  False  False  False  False  False  False  False   
399  ...  False  False  False  False  False  False  False  False  False   

     classification  
0             False  
1             False  
2             False  
3             False  
4             False  
..              ...  
395           False  
396           False  
397           False  
398           False  
399           False  

[400 rows x 26 columns]

In [ ]:
df.isnull().sum()

id                  0
age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                70
wc                105
rc                130
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

#tek tek bakmak yerine fonksiyon yapabilriz

In [ ]:
import pandas as pd

"""c=' a'
x="sinnan"
"""

def dataset_summary(df):
    """
    Bu fonksiyon, verilen DataFrame'in özet bilgilerini döndürür. #docstring
    """
    # Tanımlayıcı istatistikler
    description = df.describe()

    # Genel bilgi
    info = df.info()

    # Eksik değerlerin sayısı
    missing_values = df.isnull().sum()

    return description, info, missing_values



In [ ]:

# Örnek kullanım:
 #df = pd.read_csv('dosya_yolu.csv')
genel = dataset_summary(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   id              400 non-null    int64  
 1   age             391 non-null    float64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              354 non-null    float64
 5   su              351 non-null    float64
 6   rbc             248 non-null    object 
 7   pc              335 non-null    object 
 8   pcc             396 non-null    object 
 9   ba              396 non-null    object 
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    object 
 17  wc              295 non-null    obj

In [ ]:
genel

(               id         age          bp          sg          al          su  \
 count  400.000000  391.000000  388.000000  353.000000  354.000000  351.000000   
 mean   199.500000   51.483376   76.469072    1.017408    1.016949    0.450142   
 std    115.614301   17.169714   13.683637    0.005717    1.352679    1.099191   
 min      0.000000    2.000000   50.000000    1.005000    0.000000    0.000000   
 25%     99.750000   42.000000   70.000000    1.010000    0.000000    0.000000   
 50%    199.500000   55.000000   80.000000    1.020000    0.000000    0.000000   
 75%    299.250000   64.500000   80.000000    1.020000    2.000000    0.000000   
 max    399.000000   90.000000  180.000000    1.025000    5.000000    5.000000   
 
               bgr          bu          sc         sod         pot        hemo  
 count  356.000000  381.000000  383.000000  313.000000  312.000000  348.000000  
 mean   148.036517   57.425722    3.072454  137.528754    4.627244   12.526437  
 std     79.28171

#kidneyOrnek.ipynb